<?php if ($helpers->isAuthentificated()) : ?>
    <div class="blog-post">
        <a class="btn btn-primary" href='<?= LINK_WEB ?>jeu/create'>Ajouter un jeu</a>
    </div>
<?php endif; ?>

<?php foreach ($elements as $jeu) : ?>
    <div class="card small col s6">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="public/img/jeux/<?= $jeu->img ?>">
        </div>
        <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"><?= $jeu->nomJeux ?><i
                        class="material-icons right">more_vert</i></span>
            <p><?= $jeu->console ?></p>
            <p><a href="<?= LINK_WEB ?>jeu/read/<?= $jeu->jid ?>">Notation détaillée</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><?= $jeu->nomJeux ?><i
                        class="material-icons right">close</i></span>
            <h6>Note moyenne</h6>
            <p>Graphisme:
				<?php foreach ($notes as $note) {
					echo ($note->ID_jeux === $jeu->jid && $note->nom === 'graphisme') ? $note->noteMoy : "";
				} ?>
            </p>
            <p>Game Play:
				<?php foreach ($notes as $note) {
					echo ($note->ID_jeux === $jeu->jid && $note->nom === 'gameplay') ? $note->noteMoy : "";
				} ?>
            </p>
            <p>Durée de vie:
				<?php foreach ($notes as $note) {
					echo ($note->ID_jeux === $jeu->jid && $note->nom === 'dureevie') ? $note->noteMoy : "";
				} ?>
            </p>
            <h6>Dernier commentaires:</h6>
            <p>
                <span>Graphisme:</span>
            <ul>
				<?php foreach ($commentaires as $commentaire) {
					echo ($commentaire->ID_jeux === $jeu->jid && $commentaire->ID_criteres === "1") ? "<li>" . $commentaire->commentaires . "</li>" : "";
				} ?>
            </ul>
            <span>Gameplay:</span>
            <ul>
				<?php foreach ($commentaires as $commentaire) {
					echo ($commentaire->ID_jeux === $jeu->jid && $commentaire->ID_criteres === "2") ? "<li>" . $commentaire->commentaires . "</li>" : "";
				} ?>
            </ul>
            <span>Duree de vie: </span>
            <ul>
				<?php foreach ($commentaires as $commentaire) {
					echo ($commentaire->ID_jeux === $jeu->jid && $commentaire->ID_criteres === "3") ? "<li>" . $commentaire->commentaires . "</li>" : "";
				} ?>
            </ul>
            </p>
            <p>ajouté par: <a href="#"><?= $jeu->nomUser ?></a> le: <?= date("d/m/Y", strtotime($jeu->userUpdate)) ?></p>
        </div>
    </div>
<?php endforeach; ?>
<ul class="pagination">
    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
    <li class="active"><a href="#!">1</a></li>
    <li class="waves-effect"><a href="#!">2</a></li>
    <li class="waves-effect"><a href="#!">3</a></li>
    <li class="waves-effect"><a href="#!">4</a></li>
    <li class="waves-effect"><a href="#!">5</a></li>
    <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
</ul>
