<div>
    <h2>Create jeu</h2>
    <hr>
    <?php foreach ($errors as $e): ?>
        <div  class="alert">
            <?php echo $e ?>
        </div>
    <?php endforeach; ?>
    <form method="post">
        <div class="form-group">
            <label for="title">Title</label>
            <input value="<?php echo $helpers->foundInputValue('title') ?>" type="text" name="title" class="form-control" id="title" aria-describedby="titleHelp" placeholder="Enter title">
            <small id="titleHelp" class="form-text text-muted">Title for jeu 50 chars max.</small>
        </div>
        <div class="form-group">
            <label for="content">Content</label>
            <textarea value="<?php echo $helpers->foundInputValue('content') ?>" name="content" class="form-control" id="content" rows="15"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="<?php echo LINK_WEB ?>jeu" class="btn btn-secondary">Cancel</a>
    </form>
</div>