<div class="row">
    <div class="divider"></div>
    <div class="section">
        <h5>S'enregistrer</h5>
        <p><a class="waves-effect waves-light btn-large" href='<?= LINK_WEB ?>user/register'>Register</a></p>
    </div>
</div>
<div class="row">
    <div class="divider"></div>
    <div class="section">
        <h5>Login User</h5>
        <p>
			<?php foreach ($errors
			
			as $e) : ?>
        <div class="alert alert-danger">
			<?= $e ?>
        </div>
		<?php endforeach; ?>
        </p>
        <form class="col s12" method="post">
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">account_circle</i>
                    <input value="<?= $helpers->foundInputValue('mail') ?>" id="mail" type="email" class="validate" name="mail">
                    <label class="icon_prefix" for="email">Email</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">phone</i>
                    <input id="password" placeholder="Enter the password" type="password" class="validate" name='password'>
                    <label class="icon_prefix" for="password">Password</label>
                </div>
            </div>
            <div class="row">
                <button class="btn-large waves-effect waves-light" type="submit" name="action">Login
                    <i class="material-icons right">send</i>
                </button>
                <a href="<?= LINK_WEB ?>jeu" class="waves-effect waves-light btn-large">Cancel</a>
            </div>
        </form>
    </div>
</div>